### ISSUE TITLE
2.1.45 Beta 5 won't work

### ISSUE THREAD

**Issue by DoctorToBeIn23** [glutanimate/batch-editing#16]
![image](https://user-images.githubusercontent.com/60248099/125121430-2769a400-e0b1-11eb-87c2-557b06400ff3.jpeg)
Get this error when I try to replace text with nothing. I disabled all other add ons and issue still persisted,

**Comment by glutanimate** [comment]
Thanks for the report! Closing this issue as it should no longer be relevant for newer Anki versions.

If you run into any issues with the update I just released on AnkiWeb, please let me know.
