### ISSUE TITLE
Images change from jpg to png after batch-editing

### ISSUE THREAD

**Issue by AH349** [glutanimate/batch-editing#18]
When I use batch-editing to add images to a number of cards it turns the file from "**jpg**" to "**png**", thus increasing the file size. In my Anki preferences the "Paste clipboard images as PNG" is unchecked. I didn't find another addon that I have that may conflict or cause this. 
This however can be circumvented by placing the HTML of the image. My current Anki Version ⁨2.1.49 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

Windows 10, 64b

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*
![image](https://user-images.githubusercontent.com/99471389/166632273-44f33fe1-235f-47eb-91fb-63fa7dd10103.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Thanks for the report! This is fixed in v0.4.0. Should be up on AnkiWeb now.
