### ISSUE TITLE
Paperclip icon missing to indicate image attachment

### ISSUE THREAD

**Issue by dollajas** [glutanimate/batch-editing#22]
Running Anki 2.1.64 Qt6, tested with no other add-ons as well. On MacOS 13.4 (newest OS).

The paperclip icon to indicate that images need to be attached is missing as seen below. This issue still persists on nightmode.
 
![image](https://github.com/glutanimate/batch-editing/assets/63369555/218e16ee-4935-47e9-b637-04617d4cbaa5)

**Comment by glutanimate** [comment]
Thanks for the report! This is fixed in v0.4.0. Should be up on AnkiWeb now.
